[build]
  base = "frontendl"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[env]
  [env.production]
    VITE_API_URL = "https://studybuddy-1-sr8z.onrender.com"
    VITE_RAZORPAY_KEY_ID = "rzp_test_Sgz4NF1ltVdJMx"
